# -*- coding: utf-8 -*-
"""TOV_solve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3frrHkz2abpCXAWdHDMIZnWu_uBop-2

This jupyter notebook computes the M-R curves and the tidal deformability for the QMC-RMF1/2/3/4 relativistic mean field models as published in arxiv:XXX .
If used in colab upload the "input_data" folder as well as tov.py and constants.py as found on https://gitlab.com/ahaber/qmc-psx
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
#import matplotlib.pyplot as plt
#from matplotlib import rc
#rc('text.latex', preamble = r'\usepackage[helvet]{sfmath} \usepackage{sansmathfonts}')

# %config InlineBackend.figure_format = 'retina'

#Load TOV class
from RMFsolver.tov import *
from RMFsolver.constants import *

#Here we load the EOS data file created in Mathematica
eos1 = np.genfromtxt("QMCRMF.dat", names=True, skip_header=1)

#create EOS arrays
n_arr1, p_arr1 = eos1["energy_density"], eos1["pressure"]


#initialization of TOVsolver. Crust is included already in EOS files (TM1e + BPS)
tov_s1 = TOV(n_arr1, p_arr1, plot_eos=False, add_crust=False)

#Generate M-R curve 
m_arr1 = []
R_arr1 = []
cs_arr = []
r_arr  = []
dens_arr = []

for dens_c in np.logspace(2.2,3.3,40):
    R , M, prof, cs, rad = tov_s1.solve(dens_c, rmax=50e5, dr=100)
    m_arr1.append(M)
    R_arr1.append(R)
    cs_arr.append(cs)
    r_arr.append(rad)
    dens_arr.append(dens_c)
#Save M-R curves to file
np.savetxt("QMCRMF_MR.dat", list(zip(R_arr1,m_arr1,dens_arr)), fmt="%s")
#np.savetxt("QMH_cs.dat", cs_arr, fmt="%s")
#np.savetxt("QMH_csR.dat", r_arr, fmt="%s")


